spring:
  application:
    name: spring-keycloak
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: management_system
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/management_system
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/management_system
#          jwt-set-uri: http://localhost:8080/auth/realms/projects/protocol/openid-connect/certs

server:
  port: 9100