server:
  port: 9000

spring:
  application:
    name: spring-keycloak
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/projects
          jwt-set-uri: http://localhost:8080/auth/realms/projects/protocol/openid-connect/certs